// Generated by https://quicktype.io

export interface Catalogo {
    codigoCatalogo:     number;
    codigoUnico:        number;
    codigoPadre:        number;
    descripcion:        string;
    estado:             number;
    fechaCreacion:      null;
    fechaActualización: null;
}
